/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-Feb.-2026 19:59:47 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Area]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Equipo] DROP CONSTRAINT [FK_Equipo_Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Estado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Tipomantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Tecnico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Prioridad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrdenDeTrabajo_Mantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrdenDeTrabajo] DROP CONSTRAINT [FK_OrdenDeTrabajo_Mantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Recursos_Mantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Recursos] DROP CONSTRAINT [FK_Recursos_Mantenimiento]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Area]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Equipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Mantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Mantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[OrdenDeTrabajo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [OrdenDeTrabajo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Prioridad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Recursos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Recursos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tecnico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipomantenimiento]
GO

/* Create Tables */

CREATE TABLE [Area]
(
	[AreaID] int NOT NULL
)
GO

CREATE TABLE [Equipo]
(
	[EquipoID] int NOT NULL,
	[AreaID] int NULL
)
GO

CREATE TABLE [Estado]
(
	[EstadoID] int NOT NULL
)
GO

CREATE TABLE [Mantenimiento]
(
	[MantenimientoID] int NOT NULL,
	[EquipoID] int NULL,
	[EstadoID] int NOT NULL,
	[TipomantenimientoID] int NOT NULL,
	[TecnicoID] int NULL,
	[PrioridadID] int NOT NULL
)
GO

CREATE TABLE [OrdenDeTrabajo]
(
	[OrdenDeTrabajoID] int NOT NULL,
	[MantenimientoID] int NOT NULL
)
GO

CREATE TABLE [Prioridad]
(
	[PrioridadID] int NOT NULL
)
GO

CREATE TABLE [Recursos]
(
	[RecursosID] int NOT NULL,
	[MantenimientoID] int NOT NULL
)
GO

CREATE TABLE [Tecnico]
(
	[TecnicoID] int NOT NULL
)
GO

CREATE TABLE [Tipomantenimiento]
(
	[TipomantenimientoID] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Area] 
 ADD CONSTRAINT [PK_Area]
	PRIMARY KEY CLUSTERED ([AreaID] ASC)
GO

ALTER TABLE [Equipo] 
 ADD CONSTRAINT [PK_Equipo]
	PRIMARY KEY CLUSTERED ([EquipoID] ASC)
GO

ALTER TABLE [Estado] 
 ADD CONSTRAINT [PK_Estado]
	PRIMARY KEY CLUSTERED ([EstadoID] ASC)
GO

ALTER TABLE [Mantenimiento] 
 ADD CONSTRAINT [PK_Mantenimiento]
	PRIMARY KEY CLUSTERED ([MantenimientoID] ASC)
GO

ALTER TABLE [OrdenDeTrabajo] 
 ADD CONSTRAINT [PK_OrdenDeTrabajo]
	PRIMARY KEY CLUSTERED ([OrdenDeTrabajoID] ASC)
GO

ALTER TABLE [Prioridad] 
 ADD CONSTRAINT [PK_Prioridad]
	PRIMARY KEY CLUSTERED ([PrioridadID] ASC)
GO

ALTER TABLE [Recursos] 
 ADD CONSTRAINT [PK_Recursos]
	PRIMARY KEY CLUSTERED ([RecursosID] ASC)
GO

ALTER TABLE [Tecnico] 
 ADD CONSTRAINT [PK_Tecnico]
	PRIMARY KEY CLUSTERED ([TecnicoID] ASC)
GO

ALTER TABLE [Tipomantenimiento] 
 ADD CONSTRAINT [PK_Tipomantenimiento]
	PRIMARY KEY CLUSTERED ([TipomantenimientoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Equipo] ADD CONSTRAINT [FK_Equipo_Area]
	FOREIGN KEY ([AreaID]) REFERENCES [Area] ([AreaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Equipo]
	FOREIGN KEY ([EquipoID]) REFERENCES [Equipo] ([EquipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Estado]
	FOREIGN KEY ([EstadoID]) REFERENCES [Estado] ([EstadoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Tipomantenimiento]
	FOREIGN KEY ([TipomantenimientoID]) REFERENCES [Tipomantenimiento] ([TipomantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Tecnico]
	FOREIGN KEY ([TecnicoID]) REFERENCES [Tecnico] ([TecnicoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Prioridad]
	FOREIGN KEY ([PrioridadID]) REFERENCES [Prioridad] ([PrioridadID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrdenDeTrabajo] ADD CONSTRAINT [FK_OrdenDeTrabajo_Mantenimiento]
	FOREIGN KEY ([MantenimientoID]) REFERENCES [Mantenimiento] ([MantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Recursos] ADD CONSTRAINT [FK_Recursos_Mantenimiento]
	FOREIGN KEY ([MantenimientoID]) REFERENCES [Mantenimiento] ([MantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO
