/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-Feb.-2026 23:55:22 				*/ a
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Area]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Equipo] DROP CONSTRAINT [FK_Equipo_Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Planmantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Planmantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Estado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Tipomantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Tecnico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Prioridad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Recurso_Planmantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Recurso] DROP CONSTRAINT [FK_Recurso_Planmantenimiento]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Area]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Equipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Mantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Mantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Object1]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Object1]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Planmantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Planmantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Prioridad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Recurso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Recurso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tecnico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tecnico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipomantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipomantenimiento]
GO

/* Create Tables */

CREATE TABLE [Area]
(
	[AreaID] int NOT NULL
)
GO

CREATE TABLE [Equipo]
(
	[EquipoID] int NOT NULL,
	[AreaID] int NULL
)
GO

CREATE TABLE [Estado]
(
	[EstadoID] int NOT NULL
)
GO

CREATE TABLE [Estado]
(
	[EstadoID] int NOT NULL
)
GO

CREATE TABLE [Mantenimiento]
(
	[MantenimientoID] int NOT NULL,
	[PlanmantenimientoID] int NOT NULL
)
GO

CREATE TABLE [Object1]
(
	[Object1ID] int NOT NULL
)
GO

CREATE TABLE [Planmantenimiento]
(
	[PlanmantenimientoID] int NOT NULL,
	[EquipoID] int NULL,
	[EstadoID] int NOT NULL,
	[TipomantenimientoID] int NOT NULL,
	[TecnicoID] int NULL,
	[PrioridadID] int NOT NULL
)
GO

CREATE TABLE [Prioridad]
(
	[PrioridadID] int NOT NULL
)
GO

CREATE TABLE [Recurso]
(
	[RecursoID] int NOT NULL,
	[PlanmantenimientoID] int NOT NULL
)
GO

CREATE TABLE [Tecnico]
(
	[TecnicoID] int NOT NULL
)
GO

CREATE TABLE [Tecnico]
(
	[TecnicoID] int NOT NULL
)
GO

CREATE TABLE [Tipomantenimiento]
(
	[TipomantenimientoID] int NOT NULL
)
GO

CREATE TABLE [Tipomantenimiento]
(
	[TipomantenimientoID] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Area] 
 ADD CONSTRAINT [PK_Area]
	PRIMARY KEY CLUSTERED ([AreaID] ASC)
GO

ALTER TABLE [Equipo] 
 ADD CONSTRAINT [PK_Equipo]
	PRIMARY KEY CLUSTERED ([EquipoID] ASC)
GO

ALTER TABLE [Estado] 
 ADD CONSTRAINT [PK_Estado]
	PRIMARY KEY CLUSTERED ([EstadoID] ASC)
GO

ALTER TABLE [Estado] 
 ADD CONSTRAINT [PK_Estado]
	PRIMARY KEY CLUSTERED ([EstadoID] ASC)
GO

ALTER TABLE [Mantenimiento] 
 ADD CONSTRAINT [PK_Mantenimiento]
	PRIMARY KEY CLUSTERED ([MantenimientoID] ASC)
GO

ALTER TABLE [Object1] 
 ADD CONSTRAINT [PK_Object1]
	PRIMARY KEY CLUSTERED ([Object1ID] ASC)
GO

ALTER TABLE [Planmantenimiento] 
 ADD CONSTRAINT [PK_Planmantenimiento]
	PRIMARY KEY CLUSTERED ([PlanmantenimientoID] ASC)
GO

ALTER TABLE [Prioridad] 
 ADD CONSTRAINT [PK_Prioridad]
	PRIMARY KEY CLUSTERED ([PrioridadID] ASC)
GO

ALTER TABLE [Recurso] 
 ADD CONSTRAINT [PK_Recurso]
	PRIMARY KEY CLUSTERED ([RecursoID] ASC)
GO

ALTER TABLE [Tecnico] 
 ADD CONSTRAINT [PK_Tecnico]
	PRIMARY KEY CLUSTERED ([TecnicoID] ASC)
GO

ALTER TABLE [Tecnico] 
 ADD CONSTRAINT [PK_Tecnico]
	PRIMARY KEY CLUSTERED ([TecnicoID] ASC)
GO

ALTER TABLE [Tipomantenimiento] 
 ADD CONSTRAINT [PK_Tipomantenimiento]
	PRIMARY KEY CLUSTERED ([TipomantenimientoID] ASC)
GO

ALTER TABLE [Tipomantenimiento] 
 ADD CONSTRAINT [PK_Tipomantenimiento]
	PRIMARY KEY CLUSTERED ([TipomantenimientoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Equipo] ADD CONSTRAINT [FK_Equipo_Area]
	FOREIGN KEY ([AreaID]) REFERENCES [Area] ([AreaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Planmantenimiento]
	FOREIGN KEY ([PlanmantenimientoID]) REFERENCES [Planmantenimiento] ([PlanmantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Equipo]
	FOREIGN KEY ([EquipoID]) REFERENCES [Equipo] ([EquipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Estado]
	FOREIGN KEY ([EstadoID]) REFERENCES [Estado] ([EstadoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Tipomantenimiento]
	FOREIGN KEY ([TipomantenimientoID]) REFERENCES [Tipomantenimiento] ([TipomantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Tecnico]
	FOREIGN KEY ([TecnicoID]) REFERENCES [Tecnico] ([TecnicoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Prioridad]
	FOREIGN KEY ([PrioridadID]) REFERENCES [Prioridad] ([PrioridadID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Recurso] ADD CONSTRAINT [FK_Recurso_Planmantenimiento]
	FOREIGN KEY ([PlanmantenimientoID]) REFERENCES [Planmantenimiento] ([PlanmantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO
